<h1>Meet the Artist</h1>
<img src="graphics/danette.jpg" align="left" hspace="20" vspace="20"><p>It is important that the technician performing your permanent cosmetic procedure is not only knowledgeable in the medical field, but has a cosmetic and artistic background as well. A consultation should be required to allow you to discuss the information presented to you, and for your technician to evaluate the information concerning your health issues. This is a very good time for you to determine if you are "communicating" with each other. It is important that your particular individual needs are addressed at this time, but your artist and technician should also be willing to give you suggestions based on her expertise in the unique field.</p>

<p>Danette is held in high regard not only by her peers, but by the greater Seattle medical community as well. She has experience working directly in the office of cosmetic, plastic and reconstructive surgeons in the greater Seattle area for over 18 years. Danette has advanced certification in color theory, technical application, and advanced technique in the field of cosmetic tattoo. She has given lectures and seminars to various support groups such as the alopecia foundation. There is reassurance in knowing that you have the medical experience required of a surgeon's office to be sure all procedures are handled in a clean and sanitary environment. Proper sterilization techniques are used following the strict guidelines of the C.D.C. (Center for Disease Control).</p>

<p>Danette is a lifetime member of the Society of Permanent Cosmetic Professionals, an elite group of women and men who are dedicated to upholding the standards and ethics of the permanent cosmetic industry. This group is presently working extremely hard to pass legislation in many states to standardize health and technician training qualifications in the permanent cosmetic profession. Danette's expertise entails knowledge of many cosmetic problems. She has a wide range of clients, from allergy sufferers, alopecia clients (enabling them to regain self-esteem that so often fades with the loss of body hair), to visually impaired women, individuals with dexterity problems and women who simply are active in sports and aerobics. Also, she is able to help those in need of other kinds of color techniques such as individuals who underwent radiation treatment and women in need of breast complex restoration after mastectomy.</p>

<p>Many plastic surgeons and ophthalmologists have performed cosmetic tattooing in the past, however, most have realized that this type of work requires a knowledge of cosmetic application and is generally not cost effective for a surgeon to perform. Working hand in hand with cosmetic facial surgeons, Another You Permanent Cosmetics can now provide this service to you. Be assured, if you don't look good, I don't look good. For a consultation regarding permanent cosmetics, simply contact me at 206-354-0692 and enjoy the freedom that permanent cosmetics can provide you!</p>

<p>Schedule a consultation today! <a href="mailto:danette-permanentcosmetics@hotmail.com">email</a> or call <a href="tel:+1-206-354-0692">206.354.0692</a>.</p>